name: Sync multiple branches
on:
  push:
    branches:
      - 'prod'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge prod -> main
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: prod
          target_branch: main
          github_token: ${{ github.token }}